version: '3.8'

services:
    postgres:
      image: postgres:14
      container_name: postgres
      restart: always
      networks:
        - backend
      ports:
        - '${DB_PORT}:${DB_PORT}'
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      expose:
        - ${DB_PORT}
      

    
    api:
      container_name: 'api'
      restart: always
      build:
        context: './server'
        dockerfile: Dockerfile.dev
      ports:
        - '${API_PORT}:${API_PORT}'
      command: npm start
      networks:
        - backend
        - frontend
      depends_on:
        - postgres
      environment:
        - PORT = ${API_PORT}
        - APP_SECRET= ${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
   

    # web:
    #   container_name: 'web'
    #   restart: always
    #   stdin_open: true
    #   build:
    #     context: ./web
    #     dockerfile: Dockerfile.dev
    #   ports:
    #     - '${WEB_PORT}:${WEB_PORT}'
    #   command: npm start
    #   depends_on:
    #     - postgres
    #     - api
    #   environment:
    #     - PORT = ${WEB_PORT}
    #     - DOMAIN = api
    #     - APP_SECRET= ${APP_SECRET}



networks:
  backend:
  frontend:
volumes:
 pgdata: