version: '3.8'

services:
    postgres:
      image: postgres:14
      container_name: postgres
      restart: always
      networks:
        - api-network
      ports:
        - '${DB_PORT}:${DB_PORT}'
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      expose:
        - ${DB_PORT}
      

    
    api:
      container_name: 'api'
      restart: always
      build:
        context: './server'
        dockerfile: Dockerfile.dev
      ports:
        - '${API_PORT}:${API_PORT}'
      command: npm start
      networks:
        - api-network
      depends_on:
        - postgres
      environment:
        - PORT = ${API_PORT}
        - APP_SECRET= ${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
   

    # web:
    #   container_name: 'web'
    #   restart: always
    #   stdin_open: true
    #   build:
    #     context: ./web
    #     dockerfile: Dockerfile.dev
    #     args:
    #       PORT: ${API_PORT}
    #   ports:
    #     - '${WEB_PORT}:${WEB_PORT}'
    #   volumes:
    #     - /app/node_modules
    #   environment:
    #     - DOMAIN = ${DOMAIN}
    #     - PORT = ${WEB_PORT}
    #     - APP_SECRET= ${APP_SECRET}



networks:
 api-network:
volumes:
 pgdata: