version: '3.8'
networks:
  postgres-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
services:
    postgres:
      container_name: 'postgres'
      image: postgres:13
      restart: always
      networks:
        - postgres-network
      ports:
        - '${DB_PORT}:${DB_PORT}'
      environment:
        - DB = ${DB}
        - DB_USER = ${DB_USER}
        - DB_PASSWORD = ${DB_PASSWORD}
        - DOMAIN = ${DOMAIN}
        - DB_PORT = ${DB_PORT}
        - DB_APP_NAME = ${DB_APP_NAME}
        - DATABASE_URL = ${DATABASE_URL}
      expose:
        - '${DB_PORT}'

    # nginx:
    #   container_name: 'nginx'
    #   restart: always
    #   build:
    #     dockerfile: Dockerfile.dev
    #     context: ./nginx
    #   ports:
    #     - "3333:3333"
    #   depends_on:
    #     - web
    #     - postgres
    #     - api
    
    api:
      container_name: 'api'
      restart: always
      build:
        context: './server'
        dockerfile: Dockerfile.dev
        args:
          PORT: ${API_PORT}
      ports:
        - '${API_PORT}:${API_PORT}'
      volumes:
        - /app/node_modules
        - ./server:/app
      environment:
        - DOMAIN = ${DOMAIN}
        - PORT = ${API_PORT}
        - APP_SECRET= ${APP_SECRET}
   

    web:
      container_name: 'web'
      restart: always
      stdin_open: true
      build:
        context: ./web
        dockerfile: Dockerfile.dev
        args:
          PORT: ${API_PORT}
      ports:
        - '${WEB_PORT}:${WEB_PORT}'
      volumes:
        - /app/node_modules
      environment:
        - DOMAIN = ${DOMAIN}
        - PORT = ${WEB_PORT}
        - APP_SECRET= ${APP_SECRET}
    
