version: '3.8'
networks:
  postgres-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
services:
    postgres:
      container_name: 'postgres'
      image: postgres:13
      restart: always
      networks:
        - postgres-network
      ports:
        - '${PORT}:${PORT}'
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      expose:
        - '${PORT}'
    # nginx:
    #   container_name: 'nginx'
    #   restart: always
    #   build:
    #     dockerfile: Dockerfile.dev
    #     context: ./nginx
    #   ports:
    #     - "3050:80"
    #   depends_on:
    #     - api
    #     - web
    #     - postgres
    
    api:
      container_name: 'api'
      build:
        dockerfile: Dockerfile.dev
        context: './server'
      ports:
      - '5000:5000'
      volumes:
        - /app/node_modules
        - ./server:/app
      environment:
        - DB = ${DB}
        - DB_NAME = ${DB_NAME}
        - DB_VERSION = ${DB_VERSION}
        - DB_USER = ${DB_USER}
        - DB_PASSWORD = ${DB_PASSWORD}
        - DB_APP_NAME = ${DB_APP_NAME}
        - PORT = ${PORT}
        - DOMAIN = ${DOMAIN}
        - APP_SECRET= ${APP_SECRET}
      networks:
        - postgres-network
   

    web:
      container_name: 'web'
      stdin_open: true
      build:
        dockerfile: Dockerfile.dev
        context: ./web
      ports:
      - '3000:3000'
      volumes:
        - /app/node_modules
        - ./client:/app
