version: "3.8"
networks:
  postgres-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
services:
  ng_transaction:
    container_name: '${DB_APP_NAME}'
    image: postgres:13
    restart: always
    networks:
      - postgres-network
    ports:
      - '${PORT}:${PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - '${PORT}'
  # prisma:
  #   container_name: dockerprisma
  #   build: 
  #     context: ./                   
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - postgres-network
  #   command: >
  #     bash -c '
  #       npx prisma generate
  #       npx prisma db push
  #       npm start
  #     '
  #   depends_on:
  #     - postgres
  #   environment:
  #     PRISMA_CONFIG: |
  #       managementApiSecret: ${__YOUR_MANAGEMENT_API_SECRET__}
  #       port: ${__YOUR_PRISMA_SERVER_PORT__}
  #       databases:
  #         default:
  #           connector: ${__YOUR_DATABASE_CONNECTOR__}
  #           host: ${__YOUR_DATABASE_HOST__}
  #           port: ${__YOUR_DATABASE_PORT__}
  #           user: ${__YOUR_DATABASE_USER__}
  #           password: ${__YOUR_DATABASE_PASSWORD__}
  #           connectionLimit: ${__YOUR_CONNECTION_LIMIT__}