FROM node:18 
WORKDIR /usr/src/app
COPY ./package*.json ./
COPY prisma ./prisma/
RUN npm i
COPY . .
# RUN yarn build
# RUN npm run migrate
CMD [ "npm", "run", "start"]

# FROM node:18 as production
# ARG NODE_ENV=production
# ENV NODE_ENV=${NODE_ENV}
# WORKDIR /usr/src/app
# COPY package*.json ./
# COPY prisma ./prisma/
# RUN npm i
# COPY . .
# COPY --from=development /usr/src/app/dist ./dist
# CMD ["node", "dist/main"]
