FROM node:16.13 as builder
WORKDIR /app
COPY ./package*.json ./
RUN npm i
COPY ./ ./
RUN npm run build

FROM nginx
ARG PORT
EXPOSE $PORT
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/dist /usr/share/nginx/html
