FROM node:16.13 as builder
WORKDIR /app
COPY ./package*.json tsconfig.json ./
RUN npm i
COPY ./ ./
RUN npm run build
ARG PORT
EXPOSE $PORT
# CMD ["npm", "run", "dev"]

FROM nginx
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/dist /usr/share/nginx/html
